steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi', '-f', 'fastapi.Dockerfile', '.']
    dir: '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bot', '-f', 'bot.Dockerfile', '.']
    dir: '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bot']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastapi'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fastapi'
      - '--platform'
      - 'managed'
      - '--region'
      - '$_REGION'
      - '--memory'
      - '$_MODEL_MEMORY'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MODEL_BUCKET=qa-model-32985712,MODEL_PATH=model'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bot'
      - '--platform'
      - 'managed'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'API_URL=https://fastapi-294066974524.europe-west1.run.app,WEBHOOK_URL=https://bot-294066974524.europe-west1.run.app'
images:
  - 'gcr.io/$PROJECT_ID/fastapi'
  - 'gcr.io/$PROJECT_ID/bot'
substitutions:
  _REGION: europe-west1
  _MODEL_MEMORY: 2Gi
options:
  logging: CLOUD_LOGGING_ONLY