steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/question-answering-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/question-answering-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'qa-app', '--image', 'gcr.io/$PROJECT_ID/question-answering-app']
images:
  - 'gcr.io/$PROJECT_ID/question-answering-app'