steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/service', '.']
    dir: '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/service']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastapi'
      - '--image'
      - 'gcr.io/$PROJECT_ID/service'
      - '--platform'
      - 'managed'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MODEL_BUCKET=qa-model-32985712,MODEL_PATH=model'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/service'
      - '--platform'
      - 'managed'
      - '--region'
      - '$_REGION'
      - '--command'
      - 'python3'
      - '--args'
      - 'bot.py'
      - '--set-env-vars'
      - 'API_URL=http://fastapi'
images:
  - 'gcr.io/$PROJECT_ID/service'
substitutions:
  _REGION: europe-west1
options:
  logging: CLOUD_LOGGING_ONLY