version: "3.9"
services:
  fastapi:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - MODEL_BUCKET=qa-model-32985712
      - MODEL_PATH=model
  bot:
    build: .
    command: python3 bot.py
    depends_on:
      - fastapi
    volumes:
      - ./secrets/extractiveqa-service-accout-key.json:/app/key.json
    environment:
      - API_URL=http://fastapi:8080
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
      - GCP_PROJECT_ID=extractiveqa-442314